### ISSUE TITLE
Modernize Project and Release 2.0 to PyPI

### ISSUE THREAD

**Issue by jamadden** [zopefoundation/zope.file#1]
Meta-issue to track status.

- [x] Add Travis CI support
- [x] Add tox.ini
- [x] Drop old Python versions
   * None were ever explicitly listed, so there was nothing to do here.
- [x] Reach 100% coverage
- [x] Update/pin deps
- [x] Add PyPy support
- [x] Port to Python 3
- [x] Build universal wheels
- [x] compatibility with zest.releaser and score 10/10
- [x] Rename README/CHANGES .txt to .rst (and all the doctests)
- [ ] Move docs to RTD and simplify PyPI page (may defer?)
- [ ] Convert most doctests to real tests to cleanup docs and make testing easier (may defer).

**Comment by jamadden** [comment]
Step 0: Get tests running as-is. (Sadly they're mostly in doctests 😭 ) They have a reliance on `zope.testbrowser.testing.Browser`, which is no longer supported. For now we'll need to pin to an older version, but before the Python 3 part can happen we'll have to change. 

Here's the message:

>     NotImplementedError: zope.testbrowser.testing.Browser is no longer supported.
>
>        Please use zope.testbrowser.wsgi.Browser() in conjuction with
>        zope.app.wsgi.testlayer.BrowserLayer(), or some other custom test layer
>        that inherits from zope.testbrowser.wsgi.Layer.
>
>        Alternatively pin zope.testbrowser version to < 5.0.0 if you don't care
>        for Python 3 support and don't have the time to update your tests now.

**Comment by jamadden** [comment]
A Python 3 port is not going to be directly possible without some substantial test refactoring (needs to happen anyway). This package has a test dependency on `zope.app.container` and `zope.app.component` via zope.app.zcmlfiles`, and those two have not been ported to Python 3 yet.

Fortunately I think the only blockers are test dependencies.

**Comment by icemac** [comment]
Even the tests should not depend on `zope.app.zcmlfiles` but on the packages actually needed for `zope.file` See the following ftesting.zcml files as a possible starting point:

* https://github.com/zopefoundation/z3c.layer.ready2go/blob/master/src/z3c/layer/ready2go/ftesting.zcml
* https://github.com/zopefoundation/z3c.traverser/blob/master/src/z3c/traverser/viewlet/ftesting.zcml
* https://github.com/zopefoundation/z3c.relationfield/blob/master/src/z3c/relationfield/ftesting.zcml

**Comment by jamadden** [comment]
Thanks, that may help some, but I think we still have a dependency on `z.a.component` and `z.a.container` in order to do the actual uploads to `http://localhost/@@+/zope.app.File` (that code path is kinda cool and kinda scary at the same...I hadn't seen it before; I've mostly stayed away from a lot of the higher level `zope.app` packages). `z.a.component` is where the `@@+` view is registered, and `z.a.container` is where the guts of the view are actually implemented. Are there more modern replacements for those?

**Comment by icemac** [comment]
These views are only used to add new objects to the ZODB. It should be possible to replace `http://localhost/@@+/zope.app.File` by something like `http://localhost/addZopeAppFile.html` which gets bound to an AddForm. I know this breaks the idea of `@@+` to have a specific name space for add-views but I always ended up writing my own add-views because I could not use the plain classed defined in the `zope` packages but ones derived from them.

Hm, I grepped through the code of this package but I neither found any evidence of `zope.app.component` nor `zope.app.container`.

I only found `zope.app.testing`. Some years ago I wrote a blog post [Getting rid of zope.app.testing](https://icemac15.wordpress.com/2010/07/10/appswordpressicemac20100710get-rid-of-zope-app-testing-dependency/) which might help here as well.

**Comment by jamadden** [comment]
> Hm, I grepped through the code of this package but I neither found any evidence of zope.app.component nor zope.app.container.

They're not direct dependencies. But `contenttypes.txt` (a doctest) uses the `@@+` view.

**Comment by jamadden** [comment]
Hmm, maybe the simplest thing is to just update `z.a.component` and `z.a.container` to Python 3. It looks like all their dependencies have been ported except for `z.a.publisher` which is mostly shims at this point.

**Comment by mgedmin** [comment]
@icemac: oh that is an *excellent* blog post!  How come I've never seen it?  We should link to it from zope.testbrowser's documentation (e.g. the CHANGES.rst entry that mentions the drop of backwards compatibility).

Would anyone like to prepare a pull request?  I'm on a phone.

**Comment by jamadden** [comment]
Some of the PyPy issues appear to be due to a bug in `zope.proxy` and/or `zope.security.proxy`:
```
 File "//zope.filepypy/site-packages/zope/traversing/browser/absoluteurl.py", line 147, in breadcrumbs
        if sameProxiedObjects(context, request.getVirtualHostRoot()):
 File "//zope.filepypy/site-packages/zope/proxy/__init__.py", line 482, in py_sameProxiedObjects
        lhs = lhs._wrapped
 File "//zope.filepypy//zope/security/proxy.py", line 119, in __getattr__
        checker.check_getattr(wrapped, name)
 File "//zope.filepypy/site-packages/zope/security/checker.py", line 229, in check
        raise ForbiddenAttribute(name, object)
       - class: zope.site.folder.Folder
       - type: zope.site.folder.Folder
    ForbiddenAttribute: ('_wrapped', <zope.site.folder.Folder object at 0x00000001114225d0>)
```

**Comment by jamadden** [comment]
OK, once I fix that one (zopefoundation/zope.proxy#16) there's a bug in what looks like zope.security:

```
 File "//zope.filepypy/site-packages/zope/app/container/browser/contents.py", line 94, in listContentInfo
        return self._normalListContentsInfo()
  File "//zope.filepypy/site-packages/zope/app/container/browser/contents.py", line 120, in _normalListContentsInfo
        info = map(self._extractContentInfo, self.context.items())
 File "//zope.filepypy/site-packages/zope/security/proxy.py", line 28, in _wrapper
        checker.check(wrapped, name)
 File "//zope.filepypy/site-packages/zope/security/checker.py", line 229, in check
        raise ForbiddenAttribute(name, object)
       - class: BTrees._base._TreeItems
       - type: BTrees._base._TreeItems
    ForbiddenAttribute: ('__iter__', <BTrees._base._TreeItems object at 0x0000000112a420c8>)
```

**Comment by jamadden** [comment]
#3 removes the `z.a.zcmlfiles/container/folder/component` dependencies, and I thought everything else was ready for Python 3. But it turns out that `zope.app.publisher` is not on Python 3 yet. 😢

**Comment by papachoco** [comment]
thanks a lot Jason.. I was curious if this pkgs needs to have ZODB3 as a dependency

**Comment by jamadden** [comment]
>  I was curious if this pkgs needs to have ZODB3 as a dependency

It doesn't.

In fact, I don't think it needs any Py2-only deps. But since there are so many Py2-only test deps still I can't prove that just yet.

**Comment by jamadden** [comment]
Python 3 support arrived in #5. There are two Py2-only deps (zope.app.basicskin and zope.app.pagetemplate). I could probably continue to work around those, but I already have PRs open for Python 3 support that are ready for review and release 😄 Likewise there's a Python 3 bug in zope.mimetype that has a PR ready for review and release.

**Comment by jamadden** [comment]
All the dependencies are Python 3 and PyPy ready now, so #5 is ready to be reviewed and merged. I think I will defer doing anything with the documentation/doctests for now. So after #5 is merged, we're ready for release. I would be happy to do that if I could be granted PyPI rights ( @mgedmin ?)

**Comment by mgedmin** [comment]
I'm always happy to hand out PyPI rights like candies ;)

**Comment by jamadden** [comment]
Released as https://pypi.python.org/pypi/zope.file/1.0.0.

Thanks everyone for the helpful reviews and comments!

**Comment by papachoco** [comment]
Thanks a lot
