### ISSUE TITLE
Tests fail on Python 3.12

### ISSUE THREAD

**Issue by icemac** [zopefoundation/zope.file#13]
### What I did:

Run the tests on Python 3.12 via https://github.com/zopefoundation/zope.file/pull/12

### What I expect to happen:

Succeeding tests.

### What actually happened:

Test failures with forbidden attributes, see https://github.com/zopefoundation/zope.file/actions/runs/9379282834/job/25823967864?pr=12 for details

### What version of Python and Zope/Addons I am using:

* `master` branch of `zope.file`
* Python 3.12 on ubuntu (GHA)

**Comment by icemac** [comment]
Note: This repository is not marked as `maintained` this means it can end up archived if no-one actually needs it.

**Comment by icemac** [comment]
@zopefoundation/developers Sorry for this brought call: Is someone still using `zope.file` and is there someone willing to look into the test failues for Python 3.12?

**Comment by cjwatson** [comment]
I think this may be a zope.security bug.  On 3.11, `type()` of the `read` and `write` methods says `<class 'builtin_function_or_method`>`; on 3.12, it says `<class 'builtin_method'>`.  But, on both versions, `types.BuiltinFunctionType` and `types.BuiltinMethodType` are both `<class 'builtin_function_or_method'>`.  `builtin_method` is a subclass of `builtin_function_or_method`, but zope.security requires actual type identity.

IMO zope.security's `_default_checkers` needs tweaking.  Somehow.

**Comment by cjwatson** [comment]
I haven't actually bisected, but just from blame, my guess is that this is a consequence of the refactoring in https://github.com/python/cpython/pull/104369.

**Comment by icemac** [comment]
@cjwatson Thank you for looking into this issue. Your changes in zope.security made GHA green. 🚀
